firstapp/urls.py
# This file letting the app host it url separately

from django.urls import path
from firstapp import views

# template tagging

app_name = 'firstapp'
urlpatterns = [
    path(r'', views.index, name='index'),

    path(r'registration', views.register, name='register'),
    path(r'logout', views.user_logout, name='user_logout'),
    path(r'login', views.user_login, name='user_login'),
]

pythondjango/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from firstapp import views as main_1
from secondapp import views as hepl_1

urlpatterns = [
    # always set app index
    path('', main_1.index, name='index'),
    path(r'', include('firstapp.urls')),

    path('', hepl_1.index, name='index'),
    path(r'', include('secondapp.urls')),

    path('admin/', admin.site.urls),
]

secondapp/urls.py
from django.urls import path
from secondapp import views

app_name = 'secondapp'
urlpatterns = [
    path('help/', views.index, name='help'),
    path('blog/', views.blog, name='blog'),
]

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User


# # Create your models here.
class UserProfileInfo(models.Model):
    # create relationship (don't inherit from User)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any addition attribute you want
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        """
        Built-in attribute of django
        """
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class User(models.Model):
    user_name = models.CharField(max_length=264)

    def __str__(self):
        return self.user_name

secondapp/models.py
from django.db import models

# Create your models here.

firstapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from firstapp.models import UserProfileInfo


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')


class UserForm(forms.ModelForm):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter you email again:')
    password = forms.CharField(widget=forms.PasswordInput())
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    class Meta:
        model = User
        fields = ('username', 'name', 'email')


    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('check email')

# custom validator
# def clean_botcatcher(self):
#     botcatcher = self.cleaned_data['botcatcher']
#     if len(botcatcher) > 0:
#         raise forms.ValidationError("got you bot")
#     return botcatcher


# models form
# class NewUser(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = '__all__'

# custom validator
# def clean_botcatcher(self):
#     botcatcher = self.cleaned_data['botcatcher']
#     if len(botcatcher) > 0:
#         raise forms.ValidationError("got you bot")
#     return botcatcher

firstapp/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'firstapp/index.html')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'firstapp/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:

                return HttpResponse('Account not active')
        else:
            print("some tried to login and failed")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login detail")
    else:
        return render(request, 'firstapp/user_login.html', {})

secondapp/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    faq_dict = {'insert_me': "here is help"}

    return render(request, 'secondapp/help.html', context=faq_dict)



def blog(request):
    faq_dict = {'insert_me': "blog posted"}

    return render(request, 'secondapp/help.html', context=faq_dict)

templates/firstapp/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title></title>
</head>
<body>
<nav class=" navbar navbar-default navbar-static-top">
    <div class="container">

        <ul>
            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'firstapp:register' %}">Register</a></li>

            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'firstapp:user_logout'%}">Logout </a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'firstapp:user_login'%}">Login </a></li>
            {% endif %}

        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block%}
    {% endblock %}
</div>

</body>
</html>

templates/firstapp/header.html
<!DOCTYPE html>
<div class="">
    {% block body_block %}
    <h1>{{ text|cut: 'hello' }}</h1>
    {% endblock %}
</div>


<!--extends most be the fisrt tag in a template-->
<!--{% extends "firstapp/header.html" %}-->
    <!--{% block body_block %}-->
<!--<h1>welcome to my app</h1>-->
    <!--{% endblock %}-->

templates/firstapp/help.html
<div>
    <h1>{{ insert_me }}</h1>
</div>

templates/firstapp/index.html
{% extends "firstapp/basic.html" %}
{% block body_block %}


<div class="jumbotron">
    <h1>Django Level five</h1>
</div>

{% endblock %}

templates/firstapp/registration.html
{% extends "firstapp/basic.html" %}
{% load staticfiles %}


{% block body_block %}


<div class="jumbotron">
    {% if registered %}
    <hi>Thank you for registering!</hi>
    {% else %}
    <h1>Resgister Here</h1>
    <h3>Fill out the form</h3>


    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" class="btn btn-primary" value="Register" name="">
    </form>
    {% endif %}

</div>

{% endblock %}

templates/firstapp/scrap.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static 'css/test.css' %}">-->
    <title>Hello, world!</title>
</head>
<body>



<a href="{% url 'firstapp:index' %}">home</a>
<a href="/admin">Admin</a>
<a href="{% url 'firstapp:register' %}">register</a>
<h1>This is a picture</h1>

{{ insert_me }}
<!--<img src="{% static 'img/img1.jpg' %}" alt="office pic">-->
<h1>access records</h1>
<div class="djangtwo">
    {% if access_records %}
    <table class="table">
        <thead>
        <th scope="col">SITE NAME</th>
        <th scope="col">DATE ACCESSED</th>
        </thead>

        <tbody>
        {% for acc in access_records %}
        <tr>
            <td>{{ acc.id }}</td>
            <td>{{ acc.name }}</td>
            <td>{{ acc.date }}</td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No Access records found</p>
    {% endif %}

</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/firstapp/user.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static 'css/test.css' %}">-->
    <title>Hello, world!</title>
</head>
<body>
<h1>This is a picture</h1>
<h1>{{ context_dict }}</h1>
<div class="container">
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/firstapp/user_login.html
{% extends "firstapp/basic.html" %}
{% block body_block %}


<div class="jumbotron">
    <h1>Please Login</h1>

    <form action="{% url 'firstapp:user_login' %}" method="post">
        {% csrf_token %}
        <lable for="username">Username:</lable>
        <input type="text" name="username" placeholder="Enter Username" >

        <lable for="password">Password:</lable>
        <input type="password" name="password">

        <input type="submit" class="btn btn-primary" value="Login">

    </form>
</div>

{% endblock %}

templates/secondapp/blog.html
<div>
    <h1>{{ insert_blog }}</h1>
</div>

templates/secondapp/help.html
<div>
    <h1>{{ insert_me }}</h1>
</div>